In [4]:
import numpy as np

### 创建数组

In [21]:
data1 = [1, 2, 3, 4]
data2 = [[1, 2, 3, 4], [2, 3, 4, 5]]

arr = np.asarray([1, 2, 3, 4])
arr0 = np.array([1, 2, 3, 4])
arr1 = np.array(data1)
arr2 = np.array(data2)

arr2.shape
arr2.ndim
arr2.dtype

array([1, 2, 3, 4])

In [19]:
np.zeros(10)
np.zeros((3,6))
np.zeros((3,2,3))
np.zeros_like(arr2)    #按照arr2的维度生成一个全是0的数组
#ones()用法一样
np.empty((2,3,2))
np.arange(10)
np.eye(3)    #生成一个3*3的单位矩阵

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### 数组属性

In [37]:
arr = np.array([1, 2, 3, 4], dtype=np.float64)
int_arr = arr1.astype(np.int32)

str_arr = np.array(['1.2', '4.34', '5'], dtype=np.string_) 
num_arr = str_arr.astype(np.float)    #数值型的字符串可以直接转化为数字

int_range = np.arange(5)
f64 = np.array([1, 2, 3, 4], dtype=np.float64)
int_range.astype(f64.dtype) 
#astype是创建一个新的数组，相当于原始数据拷贝一份，所以对于原始数据并无改变，所以int_range的类型仍然是int32

array([ 0.,  1.,  2.,  3.,  4.])

### 运算

In [39]:
arr = np.array([1., 2., 3.])
arr * arr
1 / arr
arr ** 0.5    #数组中的计算都是元素级的计算

array([ 1.        ,  1.41421356,  1.73205081])

### 索引和切片

In [48]:
arr = np.arange(10)
arr_slice = arr[3:5]
arr_slice[:] = 64    
#对于原数组的切片操作是会一直保存的，所以arr的值改变了,如果不想改变arr的值需要copy()
arr_copy = arr[3:5].copy()
arr_copy[:] = 32

array([ 0,  1,  2, 64, 64,  5,  6,  7,  8,  9])

In [21]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])
arr2d[0,1]    #相当于取（0,1）处的元素
arr2d[:2, 1:]

arr2d[2]    #[5,6,7]
arr2d[2:]    #[[5,6,7]]
arr2d[2:, 1]    #[6]
arr2d[2:, 1:]    #[[6,7]]
arr2d[2, 1:]    #[6,7]
#冒号表示选取整个轴，所以这样切片之后仍然是一个二维数组，注意区别

array([6, 7])

### 布尔索引和花式索引

In [6]:
names = np.array(['bob', 'tom', 'eric', 'bob'])
data = np.random.randn(4,3)
data
names == 'bob'    #生成一个布尔型的数组
mask = (names=='bob') | (names=='tom')
data[mask] = 0

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.74026623, -1.2695329 ,  0.63461647],
       [ 0.        ,  0.        ,  0.        ]])

In [11]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])
arr2d[[1,0]]
arr2d[[2,0],[1,0]]    #取（2,1）和（0,0）两个点
arr2d[[2,0]][:, [2,0,1]]
arr2d[np.ix_([2,0],[2,0,1])]   
#根据两个一维数组进行选取，也就是一个索引器：先第2行，第0行取；每行中先取第2个，第0个，第1个

array([[7, 5, 6],
       [3, 1, 2]])

### 转置和轴对换

In [13]:
arr = np.arange(16).reshape((2, 2, 4))
arr.T

arr.transpose((1, 0, 2)) #表示第一维度和第二维度进行交换
arr.swapaxes(0, 1) #输入一对轴编号（顺序无所谓）两者发生交换

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

### 函数 

In [29]:
arr = np.arange(10)
np.sqrt(arr)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

#####  一元函数的作用
abs(fabs),sqrt,exp,log,cos,sin,sinh,cosh,tan,tanh:常用函数
square:平方
sign:计算各元素的正负号（正数1，零0，负数-1）
ceil:取各元素大于等于该值得最小整数
floor:取各元素小于等于该值得最大整数
rint:将各元素四舍五入到最接近的整数
modf:将数组的小数和整数以两个独立数组返回
isnan/isfinite/isinf:返回一个是否NaN（不是一个整数）/是否有穷/是否无穷的布尔值
logical_not:相当于-arr